### ISSUE TITLE
bug : type string of isAdapterValid function

### ISSUE THREAD

**Issue by JJDai54** [mambax7/xhelp#4]
The parametter "$name" is not as string but a boolean when click on "Faq" tab:

Erreur: TypeError: Argument 1 passed to XoopsModules/Xhelp/FaqAdapterFactory::isAdapterValid() must be of the type string, bool given, called in /modules/xhelp/class/FaqAdapterFactory.php on line 107 dans le fichier /modules/xhelp/class/FaqAdapterFactory.php ligne 156

**Comment by mambax7** [comment]
Thank you! It should be fixed in https://github.com/mambax7/xhelp/commit/065c72847f66dc84b7b545c73a5f23a08b114c75
Please test it and let me know!
